askcompany/askcompany/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView, RedirectView

urlpatterns = [
    path('',RedirectView.as_view(
        url='/instagram/'
        ),name='root'),
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls')),
    path('instagram/',include('instagram.urls')),
    path('accounts/',include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns += [
        path('__debug__/',include(debug_toolbar.urls)),
    ]

#settings.MEDIA_URL
#settings.MEDIA_ROOT

askcompany/blog/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('',views.post_list, name = 'post_list'),
] 

askcompany/instagram/urls.py
from django.urls import include,path, re_path,register_converter
from . import views
from .converters import YearConverter, MonthConverter, DayConverter

app_name = 'instagram'

register_converter(YearConverter,'year')
register_converter(MonthConverter,'month')
register_converter(DayConverter,'day')

urlpatterns = [
    path('new/',views.post_new,name='post_new'),
    path('',views.post_list,name='post_list'),
    path('<int:pk>/',views.post_detail,name='post_detail'),
    path('<int:pk>/delete/',views.post_delete,name='post_delete'),
    path('<int:pk>/edit/',views.post_edit,name='post_edit'),
    path('archive/',views.post_archive,name='post_archive'),
    path('archive/<year:year>/',views.post_archive_year,name='post_archive_year'),
]

askcompany/instagram/models.py
from django.core.validators import MinLengthValidator
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    objects = models.Manager()
    message = models.TextField(
        validators=[MinLengthValidator(10)]
    )
    photo = models.ImageField(blank=True, upload_to='instagram/post/%Y/%m/%d')
    is_public = models.BooleanField(default=False,verbose_name='공개여부')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    tag_set = models.ManyToManyField('Tag',blank=True)
    

    def __str__(self):
        return self.message

    def get_absolute_url(self):
        return reverse('instagram:post_detail',args=[self.pk])
    6

    class Meta:
        ordering = ['-id']


    def message_length(self):
        return len(self.message)
    def strpath(self):
        return 'instagram/post/%Y/%m/%d'
    message_length.short_description = "메세지 글자수" 


class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,
                                        limit_choices_to={'is_public':True})
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    pass

class Tag(models.Model):
    name = models.CharField(max_length=50,unique=True)
    #post_set = models.ManyToManyField(Post)

    def __str__(self):
        return self.name

askcompany/instagram/forms.py
from django import forms
from .models import Post
import re

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'message','photo','tag_set','is_public'
        ]

    def clean_message(self):
        message = self.cleaned_data.get('message')
        return message

askcompany/instagram/views.py
from django.views.generic import ListView, DetailView,ArchiveIndexView,YearArchiveView, CreateView,UpdateView,DeleteView
from django.shortcuts import render
from .models import Post
from django.http import HttpResponse, Http404
from django.shortcuts import get_object_or_404,redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import PostForm
from django.urls import reverse,reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

# @login_required
# def post_new(request):
#     if request.method == 'POST':
#         form = PostForm(request.POST,request.FILES)
#         if form.is_valid():
#             post = form.save(commit=False)
#             post.author = request.user
#             post.save()
#             messages.success(request,'새글이 등록되었습니다')
#             # post = form.save(commit=False)
#             # post.author = request.auther
#             # post.save()1
#             return redirect(post)
#     else:
#         form = PostForm()
#     return render(request,'instagram/post_form.html',{
#         'form':form,
#         'post':None,
#     })


class PostCreateView(LoginRequiredMixin,CreateView):
    model = Post
    form_class = PostForm

    def form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        messages.success(self.request,'새글이 등록되었습니다')
        return super().form_valid(form)

post_new = PostCreateView.as_view()


# @login_required
# def post_edit(request,pk):
#     post = get_object_or_404(Post,pk=pk)

#     #작성자 체크
#     if post.author != request.user:
#         messages.error(request,'작성자만 수정 할 수 있습니다.')
#         return redirect(post)

#     if request.method == 'POST':
#         form = PostForm(request.POST,request.FILES,instance=post)
#         if form.is_valid():
#             post = form.save()
#             messages.success(request,'포스팅을 수정했습니다')
#             return redirect(post)
#     else:
#         form = PostForm(instance=post)
#     return render(request,'instagram/post_form.html',{
#         'form':form,
#     })

class PostUpdateView(LoginRequiredMixin,UpdateView):
    model = Post
    form_class = PostForm

    def form_valid(self,form):
        messages.success(self.request,'수정 완료')
        return super().form_valid(form)
post_edit = PostUpdateView.as_view()


class PostListView(LoginRequiredMixin,ListView):
    model = Post
    paginate_by = 10
post_list = PostListView.as_view()

# @login_required
# def post_list(request):
#     qs = Post.objects.all()
#     q = request.GET.get('q','')
#     if q:
#         qs = qs.filter(message__icontains=q)
#     messages.info(request,'messages test')

#     return render(request,'instagram/post_list.html',{
#         'post_list':qs,
#         'q':q
#     })


# @login_required
# def post_list(request):
#     qs = Post.objects.all()
#     q = request.GET.get('q','')
#     if q:
#         qs = qs.filter(message__icontains=q)
#     return render(request,'instagram/post_list.html',{
#         'post_list':qs,
#         'q':q,
#     })

# def post_detail(request,pk):
#     post = get_object_or_404(Post,pk=pk)
#     # try:
#     #     post = Post.objects.get(pk=pk)  # does not exist exception
#     # except Post.DoesNotExist:
#     #     raise Http404
#     return render(request,'instagram/post_detail.html',{
#         'post':post,
#     })

# post_detail = DetailView.as_view(
#     model = Post
# )

class PostDetailView(DetailView):
    model = Post
    #queryset = Post.objects.filter(is_public=True)

    def get_queryset(self):
        qs = super().get_queryset()
        if not self.request.user.is_authenticated:
            qs = qs.filter(is_public=True)
        return qs

post_detail = PostDetailView.as_view()

post_archive = ArchiveIndexView.as_view(model=Post,date_field='created_at')

post_archive_year = YearArchiveView.as_view(model=Post,date_field='created_at',make_object_list=True)


# Create your views here.

# @login_required
# def post_delete(request,pk):
#     post = get_object_or_404(Post,pk=pk)
#     if request.method == 'POST':
#         post.delete()
#         messages.success(request,'삭제 성공 ')
#         return redirect('instagram:post_list')
#     return render(request,'instagram/post_confirm_delete.html',{
#         'post':post
#     })

class PostDeleteView(LoginRequiredMixin,DeleteView):
    model = Post
    success_url = reverse_lazy('instagram:post_list')
    # def get_success_url(self):
    #     return reverse('instagram:post_list')

post_delete = PostDeleteView.as_view()

askcompany/instagram/templates/instagram/layout.html
{%extends "layout.html"%}

askcompany/instagram/templates/instagram/post_archive.html
<h2>latest</h2>
{{latest}}

<h2>date_list</h2>
{{date_list}}

askcompany/instagram/templates/instagram/post_archive_year.html
{{year}}
<br>
{{previous_year}}
<br>
{{next_year}}
<br>
{{date_list}}
<br>
{{object_list}}

askcompany/instagram/templates/instagram/post_confirm_delete.html
{% extends 'instagram/layout.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <div class="alert alert-danger"?>
            정말 삭제하시겠습니까?
        </div>

        <a href = " {{post.get_absolute_url}}" class="btn btn-secondary">
            내용보기
        </a>

        <input type="submit" value="삭제하겠습니다." class="btn btn-danger"/>
    </form>
{% endblock %}

askcompany/instagram/templates/instagram/post_detail.html
{% extends "instagram/layout.html" %}

{%block title%}
postdetail pk#{{post.pk}}
{%endblock title%}
{%block content%}
<h2>Author:{{post.author}}</h2>

{% if post.photo %}
    <div>
        <img src="{{post.photo.url}}" />
    </div>
{% endif %}
<br>
{{post.message | linebreaks}}
<hr/>

<a href="{% url 'instagram:post_list'%}" class="btn btn-primary">
    목록
</a>
<a href="{% url 'instagram:post_edit' post.pk%}" class="btn btn-info">
    수정
</a>
<a href="{% url 'instagram:post_delete' post.pk%}" class="btn btn-danger">
    삭제
</a>

{%endblock content%}

askcompany/instagram/templates/instagram/post_form.html
{% extends "instagram/layout.html" %}
{% load bootstrap4 %}
{%block title%}title{%endblock%}
{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
{#        <table>#}
{#        {{form}}#}
{#        </table>#}
        {%buttons%}
            <button class="btn btn-primary">
                save
            </button
        {%endbuttons%}
    </form>

    {# if post #}
    {% if form.instnace %}
        <a href="{{form.instance.get_absolute_url}}" class="btn btn-primary">
            내용으로
        </a>
    {%endif%}
    <a href="{% url "instagram:post_list" %}" class="btn btn-secondary">목록으로</a>


{% endblock %}

askcompany/instagram/templates/instagram/post_list.html
{% extends "instagram/layout.html "%}
{% load bootstrap4 %}
{%block title%}
Instagram / PostList
{%endblock title%}

{%block content %}
    <form action="" method="get">
        <input type="text" name="q"/>
        <input type="submit" value="search"/>
    </form>

    <a href="{% url 'instagram:post_new' %}" class="btn btn-primary btn-block mt-3 mb-3">새글</a>

    <table class="table table-bordered table-hover">
        <tbody>
            {% for post in post_list %}
                <tr>
                    <td>
                        {{ post.pk }}
                    </td>
                    <td>
                        
                        {% if post.photo %}
                            <img src="{{ post.photo.url }}" style="width:100px"/>
                        {%else%}
                            No photo
                        {% endif %}
                    </td>
                    <td>
                        <a href="{{post.get_absolute_url}}">
                            {{ post.message }}
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {%if is_paginated %}
        {% bootstrap_pagination page_obj justify_content="center" %}
    {%endif%}
{%endblock content%}